# Main Configuration file for Monte Carlo shiny app
---
defaults:
    n_trials: 1000
    environment : |

    global : |

    init : |
        x <- uniform(min=5, max=10)
        y <- normal(sd=0.5, mean=0)
    expr: |
        x + y
    result_code: |
        ```{r}
        hist(data$.Result)
        ```
    inspect: |
        head(data, n=10)
    default_file:
        www/default.json
settings:
    welcome: no
