# Main Configuration file for Monte Carlo shiny app
---
defaults:
    n_trials: 1000
    environment : |

    global : |

    init : |
        x <- uniform(min=5, max=10)
        y <- normal(sd=0.5, mean=0)
    expr: |
        x + y
    result_code: |
        hist(results()$data$.Result)
    inspect: |
        head(results()$data, n=10)

settings:
    welcome: no
